// react-final/src/layout/Header.js
import React from "react";
import { Link } from "react-router-dom";

export default  class Header extends React.Component{
    render() {
        return (
            <>

            <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
  <div className="container-fluid">
     <a class="navbar-brand" href="#">
      <img src="https://www.datocms-assets.com/45470/1631110818-logo-react-js.png" alt="" width="90" height="60" class="d-inline-block align-text-top"/>
      
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <Link className="nav-link active" aria-current="page"  to="/">Home</Link>
        </li>
        <li class="nav-item">
        <Link className="nav-link active" aria-current="page"  to="/user">About</Link>
        </li>
        <li class="nav-item">
        <Link className="nav-link active" aria-current="page"  to="/list">Courses</Link>
        </li>
        <li class="nav-item">
        <Link className="nav-link active" aria-current="page"  to="/hooks">Hooks</Link>
        </li>
        <li class="nav-item">
        <Link className="nav-link active" aria-current="page"  to="/reg">Register</Link>
        </li>
        <li class="nav-item">
        <Link className="nav-link active" aria-current="page"  to="/login">Login</Link>
        </li>
      </ul>
    </div>
  </div>
</nav>
            </>
        )
    }
}

// learnlytica/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { LoginComponent } from '../login/login.component';





@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor(private myDialog: MatDialog) { }
  ngOnInit(): void {
  }
  openDialog() {
    const dialogRef = this.myDialog
      .open(
        LoginComponent,
        {
          height: '500px',
          width: '600px',
          disableClose: true
        }
      );

    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog result: ${result}`);
    });
  }

  

}

<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><img src="https://www.learnlytica.com/logo.png?v=14" alt="" width="250"
          height="40" class="d-inline-block align-text-top"></a>
      
    <section>
      <div class="collapse navbar-collapse"  id="navbarNavAltMarkup">
        <div class="navbar-nav">

          <a class="nav-link active" href="/course" style="color:#5755d9 ; font-size: 20px;">Course Library</a>
          <a class="nav-link active" href="/service" style="color:#5755d9 ; font-size: 20px;">Services</a>
          <a class="nav-link active" href="/contact" style="color:#5755d9 ; font-size: 20px;">Contact</a>
         
          <button mat-button (click)="openDialog()" type="button" class="btn btn-primary" style="background: #5755d9; font-size: 20px;">Login</button>
         
        
        </div>
      </div>
    </section>
    </div>
  </nav>
</div>
